### PR TITLE
:3 cs stuff bestie!!~ cs wiww win owo!~

### PR DESCRIPTION
**Pull request by 13-05**
hewwosies bestay!! i wove pwogwamming, andw i wiww win!!!

### CODE REVIEW

**Comment by 13-05** [comment]
swo faw i hawve added:

- coinfwip
- cawc-wepw

>-< owo~

**Comment by 13-05** [comment]
image

L c++ and rust

**Comment by 13-05** [comment]
alright im done for today besties

**Comment by 13-05** [comment]
also made python's calculator better and way less lines

**Review by Maou-Shimazu — APPROVED** [review]

**Review by Maou-Shimazu — APPROVED** [review]

**Pull request merged**
